# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-31 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bType', models.CharField(max_length=100)),
                ('des', models.CharField(blank=True, max_length=100)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cType', models.CharField(max_length=100)),
                ('des', models.CharField(blank=True, max_length=100)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('des', models.CharField(blank=True, max_length=200)),
                ('inuse', models.CharField(choices=[('0', '弃用'), ('1', '在用'), ('2', '未配置')], default='1', max_length=1)),
                ('modifyTime', models.DateField(auto_now=True)),
                ('bType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed.BuType')),
                ('cType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed.CategoryType')),
            ],
        ),
        migrations.CreateModel(
            name='PerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodId', models.CharField(max_length=10)),
                ('serverTime', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('NetTime', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('userId', models.CharField(blank=True, max_length=100)),
                ('deviceToken', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('phoneType', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ci', models.CharField(blank=True, max_length=100)),
                ('lo', models.CharField(blank=True, max_length=100)),
                ('la', models.CharField(blank=True, max_length=100)),
                ('ot', models.CharField(blank=True, max_length=100)),
                ('nt', models.CharField(blank=True, max_length=100)),
                ('prov', models.CharField(blank=True, max_length=100)),
                ('ver', models.CharField(blank=True, max_length=100)),
                ('tec', models.CharField(blank=True, max_length=100)),
                ('timeStamp', models.CharField(blank=True, max_length=100)),
                ('recordTime', models.DateTimeField(blank=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='secondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sType', models.CharField(max_length=100)),
                ('des', models.CharField(blank=True, max_length=100)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=1000)),
                ('method', models.CharField(blank=True, max_length=1000)),
                ('params', models.CharField(blank=True, max_length=100)),
                ('response', models.CharField(blank=True, max_length=100)),
                ('recordTime', models.DateTimeField(blank=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ints',
            name='sType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed.secondType'),
        ),
    ]
