# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='netErr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('des', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='butype',
            name='bType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='cType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ints',
            name='bType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='speed.BuType'),
        ),
        migrations.AlterField(
            model_name='ints',
            name='cType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='speed.CategoryType'),
        ),
        migrations.AlterField(
            model_name='ints',
            name='sType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='speed.secondType'),
        ),
        migrations.AlterField(
            model_name='secondtype',
            name='sType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
